node_modules/.yarn-integrity, src/App.js, src/components/Dashboard/DashboardExample.js, src/components/LoginForm.js, src/components/RegisterForm.js, src/components/modals/Modal-JobPref.js, src/components/modals/Modal-Profesional.js, src/components/modals/Modal-Profile.js, src/utils/PrivateRoute.js, src/utils/axiosWithAuth.js, yarn.lock
=> Mauricio degregori

src/App.js, src/components/Dashboard/DashboardExample.js, src/components/modals/Modal-Base.js, src/components/modals/ModalData.js
=> Refactored modal code

src/components/Dashboard/Dashboard.js, src/components/SearchBar&Filters.css, src/components/SearchBar&Filters.js
=> search bar and filter styling

src/App.js, src/components/Account/Profile.js, src/index.css, src/less/ComponentStyles/Account/Profile.less
=> changed some styling

public/css/index.css, public/index.html, src/App.js, src/components/Dashboard/Filter.js, src/less/ComponentStyles/Dashboard.less, src/less/Global/variables.less
=> finished responsive styling for dashboard

.codeclimate.yml
test of code climate testing coverage setup
=> Created .codeclimate.yml file

src/App.js, src/components/Dashboard/Dashboard.js, src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/JobDetails.js, src/components/Dashboard/Jobs/SuggestedJobs.js
=> Job details

public/css/index.css, src/less/ComponentStyles/Dashboard.less, src/less/Global/variables.less
=> fixing responsiveness of dashboard

package.json, src/components/Account/Login.js, src/components/Account/Register.js, src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/SavedJobs.js, src/components/Dashboard/Jobs/SuggestedJobs.js, yarn.lock
=> Saved jobs

public/css/index.css, src/less/ComponentStyles/Dashboard.less
=> fixing responsiveness of desktop

src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/SavedJobs.js, src/components/Dashboard/Jobs/SuggestedJobs.js
=> all save jobs functionality working

public/css/index.css, src/components/AboutUs.js, src/less/ComponentStyles/AboutUs.less
=> fixed styling on about page

public/css/index.css, src/components/Dashboard/Jobs/JobDetails.js, src/less/ComponentStyles/JobDetails.less
=> added external urls to job details

src/components/AboutUs.js
=> about page done

README.md
=> re-added code climate badges

src/less/ComponentStyles/JobDetails.less
=> fixed footer creep

public/css/index.css, src/components/AboutUs.js, src/components/Account/LandingPage.js, src/components/Account/Login.js, src/components/Account/Profile.js, src/components/Account/ProfilePicture.js, src/components/Account/Register.js, src/components/DarkMode/DarkMode-Toggle.js, src/components/DarkMode/DarkMode.js, src/components/DarkMode/LocalStorage.js, src/components/Dashboard/Dashboard.js, src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/JobDetails.js, src/components/Dashboard/Jobs/SavedJobs.js, src/components/Dashboard/Jobs/SuggestedJobs.js, src/components/Dashboard/Leftnav.js, src/less/ComponentStyles/AboutUs.less, src/less/ComponentStyles/Dashboard.less, src/less/ComponentStyles/Header.less, src/less/ComponentStyles/SavedJobs.less
=> Billy baney

src/utils/searchAPI.js
=> fixing https bug

public/css/index.css, src/components/Account/ProfilePicture.js, src/components/Dashboard/Jobs/AppliedJobs.js, src/components/Dashboard/Jobs/JobDetails.js, src/components/Footer.js, src/less/ComponentStyles/Footer.less, src/less/ComponentStyles/JobDetails.less
=> Footer fixes

src/utils/searchAPI.js
=> Filter res

package.json, public/css/index.css, src/components/Dashboard/Jobs/JobDetails.js, src/less/ComponentStyles/JobDetails.less, yarn.lock
=> added md to html functionality for the job descriptions

src/utils/searchAPI.js
=> really fixed the HTTPS bug

public/css/index.css, src/less/ComponentStyles/Dashboard.less
=> fixed styling bugs

src/components/Dashboard/Jobs/JobCard.js
=> changed title issue

src/tests/Login.test.js, src/tests/Register.test.js
=> Register test

src/components/Account/Profile.js, src/tests/Login.test.js, yarn.lock
=> Last before master

public/css/index.css, src/less/ComponentStyles/Header.less
=> changed dark mode text

src/App.js, src/components/Header.js
=> nav-about-page

src/components/Dashboard/Jobs/JobCard.js
=> no location jobs

public/css/index.css, src/components/Account/Profile.js, src/components/Account/ProfilePicture.js, src/components/DropDown.js, src/components/Header.js, src/less/ComponentStyles/Account/Profile.less, src/less/ComponentStyles/Header.less, src/less/Global/reset.less, src/less/index.less
=> profile styled, changes to the nav

public/css/index.css, src/App.js, src/components/Dashboard/Dashboard.js, src/components/Dashboard/DashboardNav.js, src/components/Dashboard/Jobs/AppliedJobs.js, src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/SavedJobs.js, src/components/Dashboard/Jobs/SuggestedJobs.js, src/components/Dashboard/Loading.js, src/components/Dashboard/RightNav.js, src/less/ComponentStyles/Account/Profile.less, src/less/ComponentStyles/Dashboard.less, src/less/ComponentStyles/Header.less, src/less/ComponentStyles/RightNav.less, src/less/ComponentStyles/SavedJobs.less, src/less/index.less, src/redux-store/App/AppActions.js, src/redux-store/App/AppReducer.js
=> new design

src/components/Dashboard/Jobs/AppliedJobs.js, src/components/Dashboard/Jobs/JobCard.js, src/components/Dashboard/Jobs/SavedJobs.js, src/components/Dashboard/Jobs/SuggestedJobs.js, src/redux-store/App/AppActions.js
=> fixed unsaving reflecting on job cards
